### ISSUE TITLE
피그마 시안짜기

### ISSUE THREAD

**Issue by yenaf** [FRONTENDSCHOOL6/dib-ReactProject#5]
- 상단 네비 (로고, 카테고리)
- 배너(이미지, 글 변경)
- 본문 글 크기, 위치, 카드 수정
- 하단 내용 변경
- 한글폰트, 영어폰트: 프리텐다드
- 포인트 컬러: 녹색
- 고정형: 완성도를 높이자!

**Comment by wlstmd1004v** [comment]
[피그마 시안](https://www.figma.com/file/6SE7VmNnymvGRP1aqx2K0A/dib?type=design&node-id=221%3A798&mode=design&t=a5nh6KgExuIrFlHn-1)
